(function(c,j){var q=c.ue_err_chan||"jserr",m="FATAL",k="v5",g=20,p=256,n=/\(?([^\s]*):(\d+):\d+\)?/,d=/.*@(.*):(\d*)/;
function o(r){if(r){return r.replace(/^\s+|\s+$/g,"");
}}function f(r){if(!r||!r.s){return;
}var s,t=r.s.length>0?r.s[0]:"",u=r.s.length>1?r.s[1]:"";
if(t){s=t.match(d);
}if((!s||s.length!=3)&&u){s=u.match(n);
}if(s&&s.length==3){r.f=s[1];
r.l=s[2];
}}function e(t,z){if(!t){return{};
}if(t.m&&t.m.message){t=t.m;
}var u={m:h(t,z),f:(t.f||t.sourceURL||t.fileName||t.filename||(t.m&&t.m.target&&t.m.target.src)),l:(t.l||t.line||t.lineno||t.lineNumber),c:t.c?""+t.c:t.c,s:[],name:t.name,type:t.type,csm:k+" "+(t.fromOnError?"onerror":"ueLogError")},y,x,s,B,v=0,w=0,r,A;
y=t.stack||(t.err?t.err.stack:"");
u.pageURL=z.pageURL||(""+(window.location?window.location.href:""))||"missing";
u.logLevel=z.logLevel||m;
A=z.attribution;
if(A){u.attribution=""+A;
}if(y&&y.split){u.csm+=" stack";
x=y.split("\n");
while(v<x.length&&u.s.length<g){s=x[v++];
if(s){u.s.push(o(s));
}}}else{u.csm+=" callee";
B=a(t.args||arguments,"callee");
v=0;
w=0;
while(B&&v<g){r=p;
if(!B.skipTrace){s=B.toString();
if(s&&s.substr){r=(w===0?4*p:r);
r=(w==1?2*p:r);
u.s.push(s.substr(0,r));
w++;
}}B=a(B,"caller");
v++;
}}if(!u.f&&u.s.length>0){f(u);
}return u;
}function h(s,r){var t=r.m||r.message||"";
if(s.m&&s.m.message){t+=s.m.message;
}else{if(s.m&&s.m.target&&s.m.target.tagName){t+="Error handler invoked by "+s.m.target.tagName+" tag";
}else{if(s.m){t+=s.m;
}else{if(s.message){t+=s.message;
}else{t+="Unknown error";
}}}}return t;
}function a(t,r){try{return t[r];
}catch(s){return;
}}function l(t,s){if(t){var r=e(t,s);
c.ue.log(r,s.channel||q,{n:1});
try{b(r);
}catch(u){}}}function b(s){var r=j.console,t=j.JSON,u="Error logged: ";
if(!r){return;
}if(t&&t.stringify){try{u+=t.stringify(s);
}catch(v){u+="no info provided; converting to string failed";
}}else{u+=s.m;
}if(typeof r.error==="function"){r.error(u,s);
}else{if(typeof r.log==="function"){r.log(u,s);
}}}function i(t,s){if((!t)||(c.ue_err.ec>c.ue_err.mxe)){return;
}c.ue_err.ec++;
c.ue_err.ter.push(t);
s=s||{};
var r=t.logLevel||s.logLevel;
s.logLevel=r;
s.attribution=t.attribution||s.attribution;
if(!r||(r==m)){ue_err.ecf++;
}l(t,s);
}l.skipTrace=1;
e.skipTrace=1;
i.skipTrace=1;
(function(){if(!c.ue_err.erl){return;
}var r=c.ue_err.erl.length,s,t;
for(s=0;
s<r;
s++){t=c.ue_err.erl[s];
l(t.ex,t.info);
}ue_err.erl=[];
})();
c.ueLogError=i;
})(ue_csm,window);
